# Generated by Django 3.2.7 on 2021-11-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_client_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_id',
        ),
    ]
